config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  get "/elephant" => "people#elephant"

  get "/people/New" => "people#New"

  get "/people" => "people#index"

  post "/people" => "people#create"

  get "/people/:id" => "people#show", as:"person"

  get "/people/:id/edit" => "people#edit", as:"people_edit"

  patch "/people/:id" => "people#update"

  delete "/people/:id" => "people#destroy" , as:"person_destroy"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController


  def New

  end

  def create
    # render plain: params[:people].inspect
    @person = Person.new(person_params)
    @person.save
    redirect_to people_path
  end

  def index
    #fetches all the db data
    @people = Person.all
  end

  def edit
    #params are used when getting information passed via the url or data being passed from the form
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    redirect_to person_path
  end

  def show
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end
  private


  def person_params
    params.require(:person).permit(:name, :age)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profileapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/New.html.erb
<h1>New Person</h1>
<form action="/people" , method= "post">
   <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >

  Name:
  <br>
  <input name=person[name] value =""></input>
  <br>
  Age:
  <br>
  <input name=person[age] value =""></input>
  <br>
  <input type="submit" value="submit">
</form>

app/views/people/edit.html.erb
<!-- <h1>New Person</h1>
<form action="/people" , method= "post">
  <input type="hidden" name="authenticity_token" value="l8C45sK7PbUoYUuySWb2JbByRVZ3TecLaNEYuEgJ4VmkrOxvZ3X5n/JiqaOn8XA49ZtozVYjJIKcmBCrRHMgaw==">
  Name:
  <br>
  <input name=people[name] value ="<%= @person[:name]%>"></input>
  <br>
  Age:
  <br>
  <input name=people[age] value ="<%= @person[:age]%>"></input>
  <br>
  <input type="submit" value="submit">
</form> -->

<%= form_with(model: @person, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/elephant.html.erb
<h1>Welcome to elephant page</h1>

app/views/people/index.html.erb
<%= link_to 'Add new person' , people_New_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @people.each do |person| %>

  <tr>
    <td><%= person.name %> </td>
    <td><%= person.age %></td>
    <td><%= link_to 'edit', people_edit_path(person) %></td>
    <td><%= link_to 'Show', person_path(person) %></td>
    <td><%= link_to 'delete', person_destroy_path(person) , method: :delete , data: {confirm:"are you sure"}%></td>
  </tr>
  <% end %>
</table>

app/views/people/show.html.erb
<p>name:</p>
<p><%= @person.name %></p>
<p>age:</p>
<p><%= @person.age %></p>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :profile_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :profile_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.age %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>